name: keepaccount_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: "3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.0
  fl_chart: 0.62.0
  intl: 0.18.1
  drag_and_drop_lists: ^0.3.3
  material_segmented_control: ^5.0.0
  http: ^1.0.0
  yaml: ^3.1.2
  fluttertoast: 8.2.2
  shared_preferences: ^2.2.0
  dio: 5.3.0
  package_info_plus: ^4.0.2
  crypto: ^3.0.3
  json_annotation: ^4.8.1
  shimmer: ^3.0.0
  flutter_easyloading: ^3.0.5
  excel: ^2.1.0
  file_picker: 6.1.1
  csv: ^5.0.2
  permission_handler: ^10.4.3
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  meta: ^1.10.0
  path_provider: 2.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:

  uses-material-design: true
  assets:
      - assets/image/share_bg.png
fonts:
  - family: SourceHanSerifCN
    fonts:
      - asset: assets/fonts/SourceHanSerifCN-Regular.otf